name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: |
        echo "Cài đặt các gói phụ thuộc..."
        npm install
    
    - name: Run tests
      run: |
        echo "Chạy kiểm thử..."
        node test.js
        echo "Kiểm thử hoàn tất thành công!"